### PR TITLE
Updated how to blog to explain how to add personal profiles and project ...

### PR DESCRIPTION
**Pull request by niallrobinson**
...pages. Should now actually be useful to point people to at their inductions.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
I wonder if it would be better to name personals profiles the same as your github username rather than `first-last`. As we open to external associates there is more of a chance of name collisions.

**Comment by niallrobinson** [comment]
Fair point but I'm not sure I agree. As there are more people on github, people end up with esoteric names. The chances of a conflict on out blog are small i think, and if it comes up, people can just deal with it the old fashioned way, by sticking an initial in or something.

**Comment by jacobtomlinson** [comment]
These names would only be visible when people add or edit their profiles. My suggestion was following the practice used in Boxen. It makes sense to stick to the same naming convention rather than introducing a new one. 

Plus I absolutely hate email addresses and other items with middle initials or even worse a "2" on the end!

**Comment by niallrobinson** [comment]
> Plus I absolutely hate email addresses and other items with middle initials or even worse a "2" on the end!
tough

I don't think using peoples actual names is a "naming convention"

**Comment by jacobtomlinson** [comment]
Well I could call `first-[initial-]last` a naming convention. But I'm happy to agree to disagree. You've been good enough to implement it so it's up to you, I was just going for consistency and ease of use.

**Comment by niallrobinson** [comment]
Whilst I respect you point, I think its better not to obfuscate things. (We can always change it relatively easily later on)

**Comment by jacobtomlinson** [comment]
No worries :smile:. Looks like another cheeky self merge though!

**Pull request merged**
