### PR TITLE
Added thumbnail pics to who we are

### PR DESCRIPTION
**Pull request by simonstanley**
Still needs some work on logic of image src, i.e. if there is an email given but they don't have a gravitar, use hexagon, not default gravitar image.

### CODE REVIEW

**Comment by niallrobinson** [comment]
hi @simonstanley I don't know if you know what Travis is? Its new to our project. Basically it runs a bunch of tests on any code you submit. You can see that this submit has failed.

If you click on the red cross you can see a report. It says that the links the the image don't have an alt tag, which is a fail. So if you just change that line then re-push, it should pass.

**Comment by niallrobinson** [comment]
p.s. that was partly because there wasn't an alt in my original code
p.p.s. I think you can actually just do little edits like that directly on the github website now.

**Comment by simonstanley** [comment]
I wonder if the alt will replace the default gavitar... that would be nice,
i'll get on it.

**Comment by jacobtomlinson** [comment]
Alt is just text to show if it can't find the image.

**Comment by simonstanley** [comment]
Yeah just realised this!

**Comment by niallrobinson** [comment]
This isn't on the live website - what the deal? @jacobtomlinson @simonstanley

**Comment by jacobtomlinson** [comment]
Perhaps GitHub Pages didn't like the _plugins directory.

**Comment by jacobtomlinson** [comment]
I'm thinking about backing this PR out. Do you thing that's a good idea? @niallrobinson @simonstanley

**Comment by niallrobinson** [comment]
if its not working, we should definitely going to extract it out for now

**Pull request merged**
