### PR TITLE
Post on volume rendering

### PR DESCRIPTION
**Pull request by niallrobinson**
Here's a first draft - I'm expecting some potentially significant feedback/changes, so don't hold back! Its a bit of a brain bender to explain at some points, so just tell me if things are unclear.

This commit also implements MathJax for rendering algebra in the markdown docs.

We should also remember to do something about hosting images rather than hot-linking to other sites (Lebera for instance), which is bad form.

### CODE REVIEW

**Comment by niallrobinson** [comment]
@alberto-arribas @simonstanley @jacobtomlinson @alastair-gemmell-lab @RPrudden You might all be interested

**Comment by jacobtomlinson** [comment]
If we were being anal the mathjax section should be in a separate pull request :stuck_out_tongue_winking_eye:.

**Comment by niallrobinson** [comment]
@jacobtomlinson that's fair. Unfortunately, I wrote the article, realised I needed to install in half way through and then finished the article. So it would have involved some kind of exotic cherry picking nonsense. But fair cop :cop: :oncoming_police_car:

**Comment by jacobtomlinson** [comment]
Nah you could just remove it in another commit and add it on another branch. Just cut and paste. 

It's not worth it for this but good practice to bear in mind.

**Pull request merged**
