### PR TITLE
Initial version of my profile

### PR DESCRIPTION
**Pull request by jacobtomlinson**

### CODE REVIEW

**Comment by niallrobinson** [comment]
:+1: when Travis comes back

**Comment by niallrobinson** [comment]
not sure why this is failing @jacobtomlinson - reeds a rebase?

**Comment by jacobtomlinson** [comment]
It is because the link on my profile to my profile is an external link and not an internal link. So the page doesn't exist yet and is failing. If converted to an internal link (as it should be) then it will find the page in the local copy. I'll fix it now.

**Comment by jacobtomlinson** [comment]
@niallrobinson @simonstanley 

The reason this PR is failing is because for some reason it has Alberto's profile (and therefore the [dirty relative link](https://github.com/met-office-lab/met-office-lab.github.io/issues/66) to his mugshot) but not the image itself. I could make the PR pass by cherry picking the PR containing the image from master but that seems a bit pointless as the image is already in master.

Could someone merge it please, it will pass once merged.

**Pull request merged**
