### PR TITLE
Second Article

### PR DESCRIPTION
**Pull request by jacobtomlinson**
I've created a second article following the [contribution process](https://github.com/met-office-lab/Lab-Info/wiki/Jekyll%20Contributing).

Hopefully someone else can check it for me!

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Don't merge yet though. Let the others check it out and see it for themselves.

**Comment by niallrobinson** [comment]
This now gets the :+1: from me and its good to go.

**Comment by jacobtomlinson** [comment]
I can't decide if I like the sheep image. I think I might prefer this one:

Sheep Two

Perhaps @msaunby could weigh in?

**Comment by niallrobinson** [comment]
If it were up to me it would be this sheep, but that's just, like, my opinion, man.
cool sheep

**Comment by niallrobinson** [comment]
Closing this because it is patently become very silly.

**Pull request closed without merging**
