### PR TITLE
Combined people and about the lab into who we are, also added Blog to na...

### PR DESCRIPTION
**Pull request by niallrobinson**
...v bar

On @alberto-arribas suggestion

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Was that a cheeky self merge :wink: ?

**Comment by niallrobinson** [comment]
@msaunby made me do it

**Comment by jacobtomlinson** [comment]
Bad @msaunby! @niallrobinson don't give into peer pressure.

We really need to take it seriously with self merges otherwise our code base will go to hell.

**Comment by niallrobinson** [comment]
You pushed to master the other day :tongue:

**Comment by niallrobinson** [comment]
but you're right, of course

**Comment by jacobtomlinson** [comment]
Haha I admit that was my mistake. I nearly rolled it back but thought it wouldn't be a problem seeings as we're squashing.

It's just something we have to enforce going forwards, especially when associated get involved.

**Pull request merged**
