### PR TITLE
added picture of magic diagram to blog post

### PR DESCRIPTION
**Pull request by niallrobinson**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
This should be a markdown tag not embedded HTML

**Comment by jacobtomlinson** [comment]
Build is also failing due to missing alt tag.

Change the line to something like
```
![3d vis diagram](https://pbs.twimg.com/media/CD6RoadXIAEuLWM.jpg:large)
```

**Comment by niallrobinson** [comment]
@jacobtomlinson tweaked

**Comment by jacobtomlinson** [comment]
@niallrobinson  have you pushed? It's only showing one commit.

**Comment by niallrobinson** [comment]
@jacobtomlinson try now - sorry

**Pull request merged**
