### PR TITLE
Removed test posts and things that didn't make sense. I'll move Alberto'...

### PR DESCRIPTION
**Pull request by niallrobinson**
...s post to some kind of concept note group folder, rather than a news post.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Looks good, ready for me to merge?

**Comment by niallrobinson** [comment]
yup

**Comment by jacobtomlinson** [comment]
I think when merging PRs we should leave the branch to be deleted by the person who created it, just in case they're not done with it.

**Comment by jacobtomlinson** [comment]
Ah you've already done it!

**Pull request merged**
