### PR TITLE
Tron style nav bar borders

### PR DESCRIPTION
**Pull request by simonstanley**
A cheeky tron design idea..

### CODE REVIEW

**Comment by niallrobinson** [comment]
Its a bold style choice, so I think we need to run it past Ross first

**Comment by jacobtomlinson** [comment]
Bold is an under statement!

**Comment by simonstanley** [comment]
Don't merge this guys. There are conflicts.

**Comment by jacobtomlinson** [comment]
We cant merge because of the conflicts :smile:

**Comment by niallrobinson** [comment]
closing for just now as part of a tidy up, but if we decide to revive it as some point in the future then we know where it is.

**Pull request closed without merging**
