### PR TITLE
Added simons profile

### PR DESCRIPTION
**Pull request by simonstanley**

### CODE REVIEW

**Comment by niallrobinson** [comment]
Hi @simonstanley

You need to change your `layout` to `profile`. I realise that its only mine that has that layout at the minute, so could you change the other profiles to `layout` while you're at it? That's why the mugshot isn't showing up.

Also, your profile pic is currently massive (full width) when it is included, so can you make it smaller. (Yu can do this easily in mac os preview). This also saves on the amount of data we need to store.

Pic name should be `firstname-secondname.png` not `firstnamesecondname.png`

Also, I think numbers under 10 should be spelled out - so `2` -> `two` (a la http://www.economist.com/styleguide/introduction)

Apart from that - it looks good.

**Comment by simonstanley** [comment]
Hows this @niallrobinson?

**Comment by niallrobinson** [comment]
try actually checking that it works (jekyll serve in your local directory then look in a browser) before you push back...image is broken because the file ending is wrong

**Comment by simonstanley** [comment]
@niallrobinson 3rd time lucky?

**Comment by niallrobinson** [comment]
you chickened out of the diabala!

**Comment by jacobtomlinson** [comment]
That [Economist Style Guide](http://www.economist.com/styleguide/introduction) needs to be included on the [How to contribute to the blog](http://www.informaticslab.co.uk/get-involved/how-to-blog/) page.

**Comment by msaunby** [comment]
And this too?  http://languagelog.ldc.upenn.edu/nll/?p=992

**Pull request merged**
